spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/masterzz/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://132.120.200.165:8761/eureka/